# Generated by Django 3.1.1 on 2020-10-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
